### ISSUE TITLE
Snapcraft error: internal system font engine problem

### ISSUE THREAD

**Issue by tttppp** [tttppp/mountain_tapir#21]
Release 5 (v1.0.2) fails to start with the following error:
```
Traceback (most recent call last):
  File "/snap/mountain-tapir/5/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/snap/mountain-tapir/5/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/snap/mountain-tapir/5/lib/python2.7/site-packages/mountain_tapir/mountain_tapir.py", line 61, in <module>
    MountainTapir(root)
  File "/snap/mountain-tapir/5/lib/python2.7/site-packages/mountain_tapir/mountain_tapir.py", line 53, in __init__
    self.recentImages = RecentImages(self.appContainer, self.controller)
  File "/snap/mountain-tapir/5/lib/python2.7/site-packages/mountain_tapir/recent_images.py", line 40, in __init__
    self.clearAllButton = TK.Button(self.recentImagesFrame, text='Clear', command=self.clearAll)
  File "/snap/mountain-tapir/5/usr/lib/python2.7/lib-tk/Tkinter.py", line 2164, in __init__
    Widget.__init__(self, master, 'button', cnf, kw)
  File "/snap/mountain-tapir/5/usr/lib/python2.7/lib-tk/Tkinter.py", line 2094, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: failed to allocate font due to internal system font engine problem
```

I didn't get this when installing the snap locally with --devmode, but I do when installing the downloaded beta channel.

When comparing with the last working version (as in #20) there are plenty of files missing from the beta snap.

**Comment by tttppp** [comment]
The problem seems to be due to the directory `$SNAP/usr/lib/x86_64-linux-gnu`.  If I replace the whole of this with the same directory from a working snap then locally I no longer see the font issue.

**Comment by tttppp** [comment]
Uploaded a manually constructed snap containing the x86_64-linux-gnu directory from snap 3 and the rest of the code generated.
