### ISSUE TITLE
f"Pillow {PILLOW_VERSION} does not support Python "

### ISSUE THREAD

**Issue by Drjacky** [tttppp/mountain_tapir#30]
```python
sudo easy_install mountain_tapir
Password:
Searching for mountain_tapir
Reading https://pypi.org/simple/mountain_tapir/
Downloading https://files.pythonhosted.org/packages/7b/9f/c1bd8f346759e09b86c6ac5da23c4d9c427c135ad929233353190f0c029c/mountain_tapir-1.1.2-py2.py3-none-any.whl#sha256=f4ac565504ee3c0a757157d4e6cfd8e283d62a728f1a723a7dc934a070dc54e6
Best match: mountain-tapir 1.1.2
Processing mountain_tapir-1.1.2-py2.py3-none-any.whl
Installing mountain_tapir-1.1.2-py2.py3-none-any.whl to /Library/Python/2.7/site-packages
writing requirements to /Library/Python/2.7/site-packages/mountain_tapir-1.1.2-py2.7.egg/EGG-INFO/requires.txt
Adding mountain-tapir 1.1.2 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/mountain_tapir-1.1.2-py2.7.egg
Processing dependencies for mountain_tapir
Searching for Pillow>=4.0.0
Reading https://pypi.org/simple/Pillow/
Downloading https://files.pythonhosted.org/packages/b0/43/3e286c93b9fa20e233d53532cc419b5aad8a468d91065dbef4c846058834/Pillow-9.0.0.tar.gz#sha256=ee6e2963e92762923956fe5d3479b1fdc3b76c83f290aad131a2f98c3df0593e
Best match: Pillow 9.0.0
Processing Pillow-9.0.0.tar.gz
Writing /tmp/easy_install-Zlv8gf/Pillow-9.0.0/setup.cfg
Running Pillow-9.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Zlv8gf/Pillow-9.0.0/egg-dist-tmp-cEER_h
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 13, in <module>
    load_entry_point('setuptools==41.0.1', 'console_scripts', 'easy_install')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 2319, in main
    **kw
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-Zlv8gf/Pillow-9.0.0/setup.py", line 46
    f"Pillow {PILLOW_VERSION} does not support Python "
                                                      ^
SyntaxError: invalid syntax
```

**Comment by tttppp** [comment]
Pillow 6.2.1 - 6.2.2 seems to be the last version(s) of Pillow to support Python 2.7. Having said that we should update Mountain Tapir to work with Python 3.

**Comment by tttppp** [comment]
Having just checked then the project already does support Python 3. Maybe the easiest fix here is to drop support for Python 2.

If you want to install against Python 2 then I suggest changing the requirements file locally to use Pillow 6.2.2.

Let me know how you get on!

**Comment by Drjacky** [comment]
My Pillow version is 8.1.0:
<img width="246" alt="Screen Shot 2022-01-28 at 10 42 04" src="https://user-images.githubusercontent.com/2296754/151533048-8f304cff-b848-452b-9abd-8e9d9f518ec8.png">

**Comment by tttppp** [comment]
Ok, but that's not compatible with Python 2.7 either. In the error message above it says 9.0.0:
```
Best match: Pillow 9.0.0
Processing Pillow-9.0.0.tar.gz
```

**Comment by tttppp** [comment]
If you have Python 3 installed then you could try using the easy install from that version instead:
https://stackoverflow.com/questions/6611730/how-to-run-easy-install-using-a-particular-python-version

**Comment by tttppp** [comment]
Hope you got it to work! Good luck!
